### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by stapelberg** [diacritic/wssdl#6]
I put wssdl.lua into `~/.config/wireshark/plugins`. When launching wireshark, I get a dialog stating:

> Lua: Error during loading: [string "/home/michael/.config/wireshark/plugins/wssdl…"]:630: attempt to index a nil value

line 630 contains:
```
      fn = luadebug.getinfo(fn).func
```

I’m running wireshark on NixOS:
```
$ wireshark --version
Wireshark 2.2.0 (Git Rev Unknown from unknown)

Copyright 1998-2016 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with Qt 4.8.7, with libpcap, with POSIX capabilities (Linux),
with libnl 3, with GLib 2.50.1, with zlib 1.2.8, without SMI, with c-ares
1.12.0, with Lua 5.2.3, with GnuTLS 3.4.15, with Gcrypt 1.7.3, without Kerberos,
with GeoIP, with QtMultimedia, without AirPcap.

Running on Linux 4.4.26, with locale LC_CTYPE=de_DE.UTF-8,
LC_NUMERIC=de_DE.UTF-8, LC_TIME=en_DK.UTF-8, LC_COLLATE=de_DE.UTF-8,
LC_MONETARY=de_DE.UTF-8, LC_MESSAGES=C, LC_PAPER=de_DE.UTF-8,
LC_NAME=de_DE.UTF-8, LC_ADDRESS=de_DE.UTF-8, LC_TELEPHONE=de_DE.UTF-8,
LC_MEASUREMENT=de_DE.UTF-8, LC_IDENTIFICATION=de_DE.UTF-8, with libpcap version
1.7.4, with GnuTLS 3.4.15, with Gcrypt 1.7.3, with zlib 1.2.8.
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (with SSE4.2)

Built using gcc 5.4.0.

```

**Comment by Snaipe** [comment]
Is this happening without any other lua file loaded? Also, could you add a `debug.traceback()` right before line 630 and paste the result here? Thanks.

**Comment by Snaipe** [comment]
Nevermind, got it. The coalesced module expected at least one lua file requiring it.

**Comment by stapelberg** [comment]
> Is this happening without any other lua file loaded?

I only have wssdl.lua in my ~/.config/wireshark/plugins, but there are a couple of lua files installed system-wide:

```
/nix/store/vcmyr13lhkfny1hrl6w3i1n76dhsr9dm-wireshark-qt-2.2.0/share/wireshark/dtd_gen.lua
/nix/store/vcmyr13lhkfny1hrl6w3i1n76dhsr9dm-wireshark-qt-2.2.0/share/wireshark/console.lua
/nix/store/vcmyr13lhkfny1hrl6w3i1n76dhsr9dm-wireshark-qt-2.2.0/share/wireshark/init.lua
```

> Also, could you add a debug.traceback() right before line 630 and paste the result here?

Done. I see the same error message (with line 631, of course). On stdout, I see:

```
1   [[string "/home/michael/.config/wireshark/plugins/wssdl..."]]:649

2   [[string "/home/michael/.config/wireshark/plugins/wssdl..."]]:630

3   [[string "/home/michael/.config/wireshark/plugins/wssdl..."]]:1116

4   <native>

5   [[string "/home/michael/.config/wireshark/plugins/wssdl..."]]:1464
```

**Comment by stapelberg** [comment]
Thanks for the quick fix. Are you going to publish a bugfix release?

**Comment by Snaipe** [comment]
I'd like to fix another issue with protocol ordering (wssdl protocols are currently added to the tree in reverse order) first, but yes, this is planned soon-ish.

**Comment by Snaipe** [comment]
v0.1.1 has been deployed to github releases! :)

**Comment by stapelberg** [comment]
Confirmed working. Thanks!
