### ISSUE TITLE
Lua Error: TvbRange:uint() does not handle 8 byte integers

### ISSUE THREAD

**Issue by stapelberg** [diacritic/wssdl#8]
I’m using the following capture file:

[repro_mlvpn.pcap.gz](https://github.com/diacritic/wssdl/files/562709/repro_mlvpn.pcap.gz)

This definition results in an error:
```
local wssdl = require 'wssdl'

pkt = wssdl.packet
{
  len : u16();
  version : bits(4);
  flags : bits(6);
  reorder : bits(1);
  unused : bits(5);
  timestamp : u16();
  timestamp_reply : u16();
  flow_id : u32();
  seq : u64();
}

wssdl.dissect {
  udp.port:add {
    [5080] = pkt:proto('mlvpn', 'multi-link VPN')
  };
}
```

Whereas this definition works (without the `seq` member):
```
local wssdl = require 'wssdl'

pkt = wssdl.packet
{
  len : u16();
  version : bits(4);
  flags : bits(6);
  reorder : bits(1);
  unused : bits(5);
  timestamp : u16();
  timestamp_reply : u16();
  flow_id : u32();
}

wssdl.dissect {
  udp.port:add {
    [5080] = pkt:proto('mlvpn', 'multi-link VPN')
  };
}
```

Am I doing something wrong?

**Comment by Snaipe** [comment]
It seems that support for integers larger than 32-bits got broken along the line (wssdl should call uint64, not uint). This should be quickly fixable.

Incidentally, this also shows that I should find a solution to test those feature.

**Comment by Snaipe** [comment]
This is now fixed. Until this hits the next release, you can use `bits(64)` as a workaround.
